<?php

namespace AppBundle\Repository;

/**
 * ArmchairRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArmchairRepository extends \Doctrine\ORM\EntityRepository
{
}
