<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EmployeeRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class EmployeeRepository extends EntityRepository
{
    public function findAllEmployees()
    {
        return $this->createQueryBuilder('e')
            ->select('e')
            ->orderBy('e.lastName', 'ASC')
            ->getQuery()
            ->getResult();
    }

}
