<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EmployeeRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class EmployeeRepository extends EntityRepository
{
    public function findAllEmployeesQuery()
    {
        return $this->createQueryBuilder('e')
            ->select('e', 'mc', 'u', 'a', 'ms', 'k', 'h', 'mo')
            ->leftJoin('e.mac', 'mc')
            ->leftJoin('e.keyboard', 'k')
            ->leftJoin('e.headphones', 'h')
            ->leftJoin('e.mouse', 'ms')
            ->leftJoin('e.usbHub', 'u')
            ->leftJoin('e.armchair', 'a')
            ->leftJoin('e.monitors', 'mo')
//            ->addSelect('COUNT(mo.id)')
            ->getQuery();
    }

    public function searchEmployees($text)
    {
        return $this->createQueryBuilder('e')
            ->select('e')
            ->where('e.lastName like :text')
            ->orWhere('e.firstName like :text')
            ->orWhere('e.fatherName like :text')
            ->orWhere('e.position like :text')
            ->setParameter('text', '%'.$text.'%')
            ->getQuery()
            ->getResult();
    }

}
