<?php

namespace AppBundle\Repository;

/**
 * HeadphonesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeadphonesRepository extends \Doctrine\ORM\EntityRepository
{
}
