<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HeadphonesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeadphonesRepository extends EntityRepository
{
    public function findFreeHeadphones()
    {
        return $this->createQueryBuilder('h')
            ->select('h, e')
            ->leftJoin('h.employee', 'e')
            ->where('e.headphones IS NULL')
            ->getQuery()
            ->getResult();
    }
}
