<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HeadphonesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeadphonesRepository extends EntityRepository
{
    public function findFreeHeadphones()
    {
        return $this->createQueryBuilder('h')
            ->select('h')
            ->where('h.employee IS NULL')
            ->getQuery()
            ->getResult();
    }
}
