<?php

namespace AppBundle\Repository;

/**
 * KeyboardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KeyboardRepository extends \Doctrine\ORM\EntityRepository
{
}
