<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * KeyboardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KeyboardRepository extends EntityRepository
{
    public function findFreeKeyboards()
    {
        return $this->createQueryBuilder('k')
            ->select('k, e')
            ->leftJoin('k.employee', 'e')
            ->where('e.keyboard IS NULL')
            ->getQuery()
            ->getResult();
    }

    public function findAllOrdered()
    {
        return $this->createQueryBuilder('k')
            ->select('k, e')
            ->leftJoin('k.employee', 'e')
            ->orderBy('e.lastName', 'ASC')
            ->getQuery()
            ->getResult();
    }
}
