<?php

namespace AppBundle\Repository;

/**
 * MacRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MacRepository extends \Doctrine\ORM\EntityRepository
{
}
