<?php

namespace AppBundle\Repository;

/**
 * MonitorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonitorRepository extends \Doctrine\ORM\EntityRepository
{
}
