<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MouseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MouseRepository extends EntityRepository
{
    public function findFreeMouses()
    {
        return $this->createQueryBuilder('m')
            ->select('m, e')
            ->leftJoin('m.employee', 'e')
            ->where('e.mouse IS NULL')
            ->getQuery()
            ->getResult();
    }

    public function findAllOrdered()
    {
        return $this->createQueryBuilder('m')
            ->select('m, e')
            ->leftJoin('m.employee', 'e')
            ->orderBy('e.lastName', 'ASC')
            ->getQuery()
            ->getResult();
    }
}
