<?php

namespace AppBundle\Repository;

/**
 * MouseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MouseRepository extends \Doctrine\ORM\EntityRepository
{
}
