<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MouseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MouseRepository extends EntityRepository
{
    public function findFreeMouses()
    {
        return $this->createQueryBuilder('m')
            ->select('m')
            ->where('m.employee IS NULL')
            ->getQuery()
            ->getResult();
    }
}
