<?php

namespace AppBundle\Repository;

/**
 * UsbHubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsbHubRepository extends \Doctrine\ORM\EntityRepository
{
}
