<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UsbHubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsbHubRepository extends EntityRepository
{
    public function findFreeUsbHubs()
    {
        return $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.employee IS NULL')
            ->getQuery()
            ->getResult();
    }
}
